name: @name@
main: @main_class@
version: @version@
authors: [ qwz ]
api-version: 1.13
depend: [ SuperiorSkyblock2 ]
soft-depend: [ PlaceholderAPI ]

commands:
  islandorbs:
    description: Main plugin command.
    aliases: [ orbs, orb, islandorb ]